{% set name = "dot2tex" %}
{% set version = "2.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dot2tex-{{ version }}.tar.gz
  sha256: 11b097390b94d1a6f5072c08c50637e724e2f81b463794972c3d423005b5f536

build:
  number: 0
  noarch: python
  entry_points:
    - dot2tex = dot2tex.dot2tex:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pyparsing
    - python >={{ python_min }}

test:
  imports:
    - dot2tex.dot2tex
    - dot2tex.dotparsing
  commands:
    - pip check
    - dot2tex --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kjellmf/dot2tex
  summary: A Graphviz to LaTeX converter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ProfLeao
    - bjodah
